package net.liuchenfei.ssitest.daos;

import net.liuchenfei.ssitest.entitys.Directory;
import net.liuchenfei.ssitest.entitys.DirectoryExample;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DirectoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int countByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int deleteByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String directoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int insert(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int insertSelective(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    List<Directory> selectByExample(DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    Directory selectByPrimaryKey(String directoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Directory record, @Param("example") DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Directory record, @Param("example") DirectoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Directory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Directory record);

    @Delete("delete from directory where directory_id in #{ids}")
    int deleteBatch(@Param("ids") String ids);
}