package net.liuchenfei.ssitest.daos;

import java.util.List;
import net.liuchenfei.ssitest.entitys.Partitions;
import net.liuchenfei.ssitest.entitys.PartitionsExample;
import org.apache.ibatis.annotations.Param;

public interface PartitionsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int countByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int deleteByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(String partitionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int insert(Partitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int insertSelective(Partitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    List<Partitions> selectByExample(PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    Partitions selectByPrimaryKey(String partitionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Partitions record, @Param("example") PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Partitions record, @Param("example") PartitionsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Partitions record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Partitions record);
}