package net.liuchenfei.ssitest.entitys;

import java.util.Date;

public class Directory {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.directory_id
     *
     * @mbggenerated
     */
    private String directoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.directory_name
     *
     * @mbggenerated
     */
    private String directoryName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.parent_directory_id
     *
     * @mbggenerated
     */
    private String parentDirectoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column directory.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    public Directory(String directoryId, String userId, String directoryName, String parentDirectoryId, Date createtime) {
        this.directoryId = directoryId;
        this.userId = userId;
        this.directoryName = directoryName;
        this.parentDirectoryId = parentDirectoryId;
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table directory
     *
     * @mbggenerated
     */
    public Directory() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.directory_id
     *
     * @return the value of directory.directory_id
     *
     * @mbggenerated
     */
    public String getDirectoryId() {
        return directoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.directory_id
     *
     * @param directoryId the value for directory.directory_id
     *
     * @mbggenerated
     */
    public void setDirectoryId(String directoryId) {
        this.directoryId = directoryId == null ? null : directoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.user_id
     *
     * @return the value of directory.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.user_id
     *
     * @param userId the value for directory.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.directory_name
     *
     * @return the value of directory.directory_name
     *
     * @mbggenerated
     */
    public String getDirectoryName() {
        return directoryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.directory_name
     *
     * @param directoryName the value for directory.directory_name
     *
     * @mbggenerated
     */
    public void setDirectoryName(String directoryName) {
        this.directoryName = directoryName == null ? null : directoryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.parent_directory_id
     *
     * @return the value of directory.parent_directory_id
     *
     * @mbggenerated
     */
    public String getParentDirectoryId() {
        return parentDirectoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.parent_directory_id
     *
     * @param parentDirectoryId the value for directory.parent_directory_id
     *
     * @mbggenerated
     */
    public void setParentDirectoryId(String parentDirectoryId) {
        this.parentDirectoryId = parentDirectoryId == null ? null : parentDirectoryId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column directory.createTime
     *
     * @return the value of directory.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column directory.createTime
     *
     * @param createtime the value for directory.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}