package net.liuchenfei.ssitest.entitys;

import java.util.Date;

public class File {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_id
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_size
     *
     * @mbggenerated
     */
    private Long fileSize;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_type
     *
     * @mbggenerated
     */
    private Integer fileType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.file_status
     *
     * @mbggenerated
     */
    private Integer fileStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.content_type
     *
     * @mbggenerated
     */
    private String contentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column file.check_code
     *
     * @mbggenerated
     */
    private String checkCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    public File(String fileId, String fileName, Long fileSize, String userId, Date uploadTime, Integer fileType, Integer fileStatus, String contentType, String checkCode) {
        this.fileId = fileId;
        this.fileName = fileName;
        this.fileSize = fileSize;
        this.userId = userId;
        this.uploadTime = uploadTime;
        this.fileType = fileType;
        this.fileStatus = fileStatus;
        this.contentType = contentType;
        this.checkCode = checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table file
     *
     * @mbggenerated
     */
    public File() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_id
     *
     * @return the value of file.file_id
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_id
     *
     * @param fileId the value for file.file_id
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_name
     *
     * @return the value of file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_name
     *
     * @param fileName the value for file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_size
     *
     * @return the value of file.file_size
     *
     * @mbggenerated
     */
    public Long getFileSize() {
        return fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_size
     *
     * @param fileSize the value for file.file_size
     *
     * @mbggenerated
     */
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.user_id
     *
     * @return the value of file.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.user_id
     *
     * @param userId the value for file.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.upload_time
     *
     * @return the value of file.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.upload_time
     *
     * @param uploadTime the value for file.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_type
     *
     * @return the value of file.file_type
     *
     * @mbggenerated
     */
    public Integer getFileType() {
        return fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_type
     *
     * @param fileType the value for file.file_type
     *
     * @mbggenerated
     */
    public void setFileType(Integer fileType) {
        this.fileType = fileType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.file_status
     *
     * @return the value of file.file_status
     *
     * @mbggenerated
     */
    public Integer getFileStatus() {
        return fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.file_status
     *
     * @param fileStatus the value for file.file_status
     *
     * @mbggenerated
     */
    public void setFileStatus(Integer fileStatus) {
        this.fileStatus = fileStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.content_type
     *
     * @return the value of file.content_type
     *
     * @mbggenerated
     */
    public String getContentType() {
        return contentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.content_type
     *
     * @param contentType the value for file.content_type
     *
     * @mbggenerated
     */
    public void setContentType(String contentType) {
        this.contentType = contentType == null ? null : contentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column file.check_code
     *
     * @return the value of file.check_code
     *
     * @mbggenerated
     */
    public String getCheckCode() {
        return checkCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column file.check_code
     *
     * @param checkCode the value for file.check_code
     *
     * @mbggenerated
     */
    public void setCheckCode(String checkCode) {
        this.checkCode = checkCode == null ? null : checkCode.trim();
    }
}