package net.liuchenfei.ssitest.entitys;

public class Partitions {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partitions.partition_id
     *
     * @mbggenerated
     */
    private String partitionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partitions.partition_index
     *
     * @mbggenerated
     */
    private Integer partitionIndex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partitions.partition_loc
     *
     * @mbggenerated
     */
    private String partitionLoc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column partitions.file_id
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    public Partitions(String partitionId, Integer partitionIndex, String partitionLoc, String fileId) {
        this.partitionId = partitionId;
        this.partitionIndex = partitionIndex;
        this.partitionLoc = partitionLoc;
        this.fileId = fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table partitions
     *
     * @mbggenerated
     */
    public Partitions() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partitions.partition_id
     *
     * @return the value of partitions.partition_id
     *
     * @mbggenerated
     */
    public String getPartitionId() {
        return partitionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partitions.partition_id
     *
     * @param partitionId the value for partitions.partition_id
     *
     * @mbggenerated
     */
    public void setPartitionId(String partitionId) {
        this.partitionId = partitionId == null ? null : partitionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partitions.partition_index
     *
     * @return the value of partitions.partition_index
     *
     * @mbggenerated
     */
    public Integer getPartitionIndex() {
        return partitionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partitions.partition_index
     *
     * @param partitionIndex the value for partitions.partition_index
     *
     * @mbggenerated
     */
    public void setPartitionIndex(Integer partitionIndex) {
        this.partitionIndex = partitionIndex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partitions.partition_loc
     *
     * @return the value of partitions.partition_loc
     *
     * @mbggenerated
     */
    public String getPartitionLoc() {
        return partitionLoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partitions.partition_loc
     *
     * @param partitionLoc the value for partitions.partition_loc
     *
     * @mbggenerated
     */
    public void setPartitionLoc(String partitionLoc) {
        this.partitionLoc = partitionLoc == null ? null : partitionLoc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column partitions.file_id
     *
     * @return the value of partitions.file_id
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column partitions.file_id
     *
     * @param fileId the value for partitions.file_id
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }
}