package net.liuchenfei.ssitest.entitys;

import java.util.Date;

public class UserFile {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.id
     *
     * @mbggenerated
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.user_id
     *
     * @mbggenerated
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_id
     *
     * @mbggenerated
     */
    private String fileId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.upload_time
     *
     * @mbggenerated
     */
    private Date uploadTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.dir_id
     *
     * @mbggenerated
     */
    private String dirId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_file.file_name
     *
     * @mbggenerated
     */
    private String fileName;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbggenerated
     */
    public UserFile(String id, String userId, String fileId, Date uploadTime, String dirId, Integer status, String fileName) {
        this.id = id;
        this.userId = userId;
        this.fileId = fileId;
        this.uploadTime = uploadTime;
        this.dirId = dirId;
        this.status = status;
        this.fileName = fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_file
     *
     * @mbggenerated
     */
    public UserFile() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.id
     *
     * @return the value of user_file.id
     *
     * @mbggenerated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.id
     *
     * @param id the value for user_file.id
     *
     * @mbggenerated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.user_id
     *
     * @return the value of user_file.user_id
     *
     * @mbggenerated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.user_id
     *
     * @param userId the value for user_file.user_id
     *
     * @mbggenerated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_id
     *
     * @return the value of user_file.file_id
     *
     * @mbggenerated
     */
    public String getFileId() {
        return fileId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_id
     *
     * @param fileId the value for user_file.file_id
     *
     * @mbggenerated
     */
    public void setFileId(String fileId) {
        this.fileId = fileId == null ? null : fileId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.upload_time
     *
     * @return the value of user_file.upload_time
     *
     * @mbggenerated
     */
    public Date getUploadTime() {
        return uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.upload_time
     *
     * @param uploadTime the value for user_file.upload_time
     *
     * @mbggenerated
     */
    public void setUploadTime(Date uploadTime) {
        this.uploadTime = uploadTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.dir_id
     *
     * @return the value of user_file.dir_id
     *
     * @mbggenerated
     */
    public String getDirId() {
        return dirId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.dir_id
     *
     * @param dirId the value for user_file.dir_id
     *
     * @mbggenerated
     */
    public void setDirId(String dirId) {
        this.dirId = dirId == null ? null : dirId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.status
     *
     * @return the value of user_file.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.status
     *
     * @param status the value for user_file.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_file.file_name
     *
     * @return the value of user_file.file_name
     *
     * @mbggenerated
     */
    public String getFileName() {
        return fileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_file.file_name
     *
     * @param fileName the value for user_file.file_name
     *
     * @mbggenerated
     */
    public void setFileName(String fileName) {
        this.fileName = fileName == null ? null : fileName.trim();
    }
}